### ISSUE TITLE
Error saving calibration

### ISSUE THREAD

**Issue by CamDavidsonPilon** [odcambc/od_standards_calibration_plugin#1]
When running this plugin, it fails on the save with:

```
  File "/usr/local/lib/python3.9/dist-packages/od_standards_calibration_plugin/od_calibration_from_standards.py", line 392, in od_calibration_from_standards
    data_blob = save_results(
  File "/usr/local/lib/python3.9/dist-packages/od_standards_calibration_plugin/od_calibration_from_standards.py", line 324, in save_results
    data_blob = struct(
TypeError: Unexpected keyword argument 'od600_values'
```
Source of error is [here](https://github.com/odcambc/od_standards_calibration_plugin/blob/main/od_standards_calibration_plugin/od_calibration_from_standards.py#LL336C26). I'm fairly sure that `od600_values` should be `inferred_od600s`, ex: 

```python
        voltages=voltages,
        inferred_od600s=od600_values,
        ir_led_intensity=float(config["od_config"]["ir_led_intensity"]),
```

In my opinion, this is a Pioreactor app problem! We didn't make these Calibration structs general enough for different calibration designs. I propose that we align on the following struct:

```python
class ODCalibration(Calibration):
    angle: pt.PdAngle
    maximum_od600: float
    minimum_od600: float
    minimum_voltage: float
    maximum_voltage: float
    curve_type: str
    curve_data_: list[float]
    voltages: list[float]
-   inferred_od600s: list[float]
+   od600s: list[float]  # change here. od600s matches voltages.
    ir_led_intensity: float
    pd_channel: pt.PdChannel
```

What do you think?

**Comment by odcambc** [comment]
Thanks - I clearly need to add some tests. I think that change to the struct makes sense! 

Fixing for now but I'll leave this open in case ODCalibration changes.

Fixed in [bf30725](https://github.com/odcambc/od_standards_calibration_plugin/commit/bf307259fec91c60d129a149986f213bfdcacfde)

**Comment by CamDavidsonPilon** [comment]
👋 in the latest release, we've changed the struct to have the field `od600s` instead of `inferred_od600s`.

**Comment by odcambc** [comment]
Updated for v1.0.2!
